### ISSUE TITLE
Refactoring for Channels 2

### ISSUE THREAD

**Issue by morlandi** [yakky/channeled-dashboard#1]
Thank you for sharing this example.
Just wondering ... being an example project, it's targeted to beginners.
But what's the point in learning the legacy Channels 1 today, given that Channels 2 is a major rewrite ?

**Comment by yakky** [comment]
Channels 2 has been released too late to be included in my talk for the Swiss python summit last week (for which this example application has been written)
I'm obviously working in the channels 2 version of the talk (and the application) for pycon Italia in April
I guess I could have the refactoring ready sometime in march

**Comment by morlandi** [comment]
Nice. I'm so glad I started using Channels when Channel2 was already available :)

**Comment by morlandi** [comment]
@yakky did you make any progress ? 
I noticed you're giving a talk on this at DjangoCon Europe 2018 in Heidelberg. Thank you (I'm attending it).
Should you need some help for testing, let me know. I'm currently working with django-channels 2

**Comment by yakky** [comment]
Hi @morlandi channels 2 branch is up (it's not final, I have yet to decide what to do with the removed binding feature)
I'll happily talk about it before, during, and after djangoconeu!

**Comment by morlandi** [comment]
nice to know :)
ciaooooo

**Comment by morlandi** [comment]
Hello @yakky, I did some tests on a production server;
a sample ansible procedure is available here:

https://github.com/morlandi/channeled-dashboard_deployment

While channels1 branch works as expected, with channels2 only the user's counter seems to be working, while the "write" flag to detect document editing never gets triggered.

You can check both behaviours here:

- http://channeled-dashboard-demo1.brainstorm.it/
- http://channeled-dashboard-demo2.brainstorm.it/

authenticating as guest1/guest1 and guest2/guest2 (on both instances).

The same behaviour occurs on local development instances (runserver).

Finally, I noticed a significant activity on redis for "channels1" instance:

```
# redis-cli monitor
OK
1525251573.422067 [0 127.0.0.1:34676] "EVALSHA" "3640886a0c8901ca9188f5f7a5f7a346145b9c5f" "1" "demo1:daphne.response.BhypArrriR!"
1525251573.422143 [0 lua] "LPOP" "demo1:daphne.response.BhypArrriR!"
1525251573.472845 [0 127.0.0.1:34676] "EVALSHA" "3640886a0c8901ca9188f5f7a5f7a346145b9c5f" "1" "demo1:daphne.response.BhypArrriR!"
1525251573.472877 [0 lua] "LPOP" "demo1:daphne.response.BhypArrriR!"
1525251573.523586 [0 127.0.0.1:34676] "EVALSHA" "3640886a0c8901ca9188f5f7a5f7a346145b9c5f" "1" "demo1:daphne.response.BhypArrriR!"
1525251573.523617 [0 lua] "LPOP" "demo1:daphne.response.BhypArrriR!"
1525251573.543323 [0 127.0.0.1:34970] "BLPOP" "demo2:specific.ucTqztXK!" "5"
1525251573.574228 [0 127.0.0.1:34676] "EVALSHA" "3640886a0c8901ca9188f5f7a5f7a346145b9c5f" "1" "demo1:daphne.response.BhypArrriR!"
1525251573.574258 [0 lua] "LPOP" "demo1:daphne.response.BhypArrriR!"
1525251573.624908 [0 127.0.0.1:34676] "EVALSHA" "3640886a0c8901ca9188f5f7a5f7a346145b9c5f" "1" "demo1:daphne.response.BhypArrriR!"
1525251573.624952 [0 lua] "LPOP" "demo1:daphne.response.BhypArrriR!"
1525251573.675696 [0 127.0.0.1:34676] "EVALSHA" "3640886a0c8901ca9188f5f7a5f7a346145b9c5f" "1" "demo1:daphne.response.BhypArrriR!"
1525251573.675728 [0 lua] "LPOP" "demo1:daphne.response.BhypArrriR!"
1525251573.726408 [0 127.0.0.1:34676] "EVALSHA" "3640886a0c8901ca9188f5f7a5f7a346145b9c5f" "1" "demo1:daphne.response.BhypArrriR!"
1525251573.726453 [0 lua] "LPOP" "demo1:daphne.response.BhypArrriR!"
1525251573.777205 [0 127.0.0.1:34676] "EVALSHA" "3640886a0c8901ca9188f5f7a5f7a346145b9c5f" "1" "demo1:daphne.response.BhypArrriR!"
1525251573.777280 [0 lua] "LPOP" "demo1:daphne.response.BhypArrriR!"
1525251573.827911 [0 127.0.0.1:34676] "EVALSHA" "3640886a0c8901ca9188f5f7a5f7a346145b9c5f" "1" "demo1:daphne.response.BhypArrriR!"
1525251573.827954 [0 lua] "LPOP" "demo1:daphne.response.BhypArrriR!"

```

is this to be expected ?


P.S. should you want to investigate further, I can provide you the credential to access the remote server. In case, contact me in private.

**Comment by yakky** [comment]
@morlandi wow, thanks! :tada: 
Would you care to open a separate issue for the channels2 problem?
The high redis traffic on channels1 is expected, it's one of the major bottlenecks of channels1: every message is read / written to redis multiple times due to serialization / deserialization

**Comment by morlandi** [comment]
yes sir :)

See issue #5
